### ISSUE TITLE
사용 하는 방법 알려주실 수 있으신가요.. 

### ISSUE THREAD

**Issue by haruskai2** [gunyu1019/PUBG-BOT#29]
discord-extension-interaction-main 파일을 받아 
PUBG-BOT 폴더에 discord 파일을 넣고 실행하니
|   File "PUBG-BOT\utils\token.py", line 27, in <module>
|     cur = connect.cursor(pymysql.cursors.DictCursor)
| AttributeError: 'NoneType' object has no attribute 'cursor'
에러가 나타납니다.

**Comment by gunyu1019** [comment]
해당 이슈는 데이터베이스가 연결되지 않아 변수에 None값이 반환되었고, Nonetype의 커서는 존재하지 않기 때문에, 발생하는 트레이스백입니다. 오류가 아닙니다 :(
